package com.ui;

import java.awt.event.ActionListener;

/**
 * @author Master
 */
public abstract class FrmUI extends javax.swing.JFrame implements ActionListener{

    public FrmUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        carac_fisica = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        carac_tec = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        carac_tat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        carac_psic = new javax.swing.JComboBox<>();
        execute = new javax.swing.JButton();
        explain = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        explainResult = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho - RNA");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Características físicas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, -1));

        carac_fisica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elasticidade", "Força", "Resistência", "Resistência aeróbica", "Agilidade" }));
        jPanel1.add(carac_fisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 250, -1));

        jLabel2.setText("Características técnicas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        carac_tec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reposição de bola com as mãos e pés", "Cabeceio", "Precisão nos passe e cruzamentos", "Passe", "Finalização" }));
        jPanel1.add(carac_tec, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 250, -1));

        jLabel3.setText("Características táticas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, -1));

        carac_tat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Posicionamento", "Domínio de espaço", "Noção de cobertura", "Domínio de ataque e defesa", "Noções de impedimento e criação de espaços" }));
        jPanel1.add(carac_tat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 250, -1));

        jLabel4.setText("Características psicológicas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 20));

        carac_psic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concentração", "Maturidade", "Controle emocional", "Combatividade", "Agressividade" }));
        jPanel1.add(carac_psic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 250, -1));

        execute.setText("Buscar");
        execute.addActionListener(this);
        jPanel1.add(execute, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 100, -1));
        jPanel1.add(explain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 410, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Selecione as informações para que o sistema reconheça algum padrão!");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jScrollPane2.setViewportView(explainResult);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 380, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox<String> carac_fisica;
    protected javax.swing.JComboBox<String> carac_psic;
    protected javax.swing.JComboBox<String> carac_tat;
    protected javax.swing.JComboBox<String> carac_tec;
    protected javax.swing.JButton execute;
    protected javax.swing.JLabel explain;
    protected javax.swing.JTextPane explainResult;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    protected javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
